[package]
name = "executable_memory"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

keywords = ["executable", "memory", "windows"]
categories = ["memory-management", "no-std"]

description = "executable memory for windows and unix"
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/nathanfaucett/rs-executable_memory.git"
homepage = "https://gitlab.com/nathanfaucett/rs-executable_memory"


[dependencies]
libc = { version = "0.2" }
winapi = { version = "0.3" }

[dev-dependencies]
